### ISSUE TITLE
Problem with Intel XDK

### ISSUE THREAD

**Issue by kamiloc** [brody4hire/cordova-sqlite-storage-dependencies#1]
I try to add this plugin in a cordova projecto from Intel XDK, but when add the plugin i find this error: 
"Cannot find plugin.xml for plugin "1473782382480". Please try adding it again."
How to solve it (?)

**Comment by brody2consult** [comment]
As documented in Cordova-sqlite-storage it does _not_ support Intel XDK, PhoneGap CLI, PhoneGap Build, etc. The following options should work:
- https://github.com/litehelpers/Cordova-sqlite-legacy-build-support
- https://github.com/litehelpers/Cordova-sqlite-evcore-extbuild-free (available under different licensing terms)
